authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('edit/<int:pk>/', authapp.EditView.as_view(), name='edit'),
    path('logout/', authapp.logout, name='logout'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('auth/', include('authapp.urls',  namespace='auth')),
    path('admin/', admin.site.urls),
]

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
]

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class ShopUser(AbstractUser):
    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    avatar = models.ImageField(upload_to="users_avatars", blank=True)
    age = models.PositiveIntegerField(verbose_name='Age')

    def __str__(self):
        return self.username

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(verbose_name="category name", max_length=55)
    description = models.TextField(verbose_name="category description", blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="product name", max_length=55)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name="", max_length=60, blank=True)
    description = models.TextField(verbose_name="product description", blank=True)
    price = models.DecimalField(verbose_name="price", max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name="storage", default=0)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

authapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import forms

from .models import ShopUser


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("You're too young!")

        return data

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic.edit import UpdateView
from django.contrib import auth
from django.urls import reverse, reverse_lazy
from .forms import ShopUserRegisterForm
from .models import ShopUser


def register(request):
    title = 'Registration'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            user = register_form.save()
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main'))
    else:
        register_form = ShopUserRegisterForm()

    context = {'title': title, 'form': register_form}
    return render(request, 'authapp/register.html', context)


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main'))

    return render(request, 'authapp/login.html')


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


class EditView(UpdateView):
    model = ShopUser
    template_name = 'authapp/register.html'
    fields = 'username', 'email', 'avatar '
    success_url = reverse_lazy('main')

mainapp/views.py
from django.shortcuts import render
import json
import os
from .models import Product
from .models import ProductCategory

JSON_PATH = 'mainapp/json'


def loadMenuFromJSON():
    with open(os.path.join(JSON_PATH, 'menu.json'), 'r') as infile:
        return json.load(infile)


def main(request):
    links_menu = loadMenuFromJSON()
    context = {'links_menu': links_menu, 'username': 'roksana', 'array': [1, 2, 3, 4, 5]}
    print(links_menu)
    return render(request, 'mainapp/main.html', context)


def products(request):
    links_menu = loadMenuFromJSON()
    context = {'links_menu': links_menu, 'products': Product.objects.all()}
    print(links_menu)
    return render(request, 'mainapp/products.html', context)


def contacts(request):
    links_menu = loadMenuFromJSON()
    context = {'links_menu': links_menu}
    return render(request, 'mainapp/contacts.html', context)

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
<div class="container">
    <div class="login">
        {% block content %}

        {% endblock %}
    </div>

</div>
</body>
</html>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}

{% block content %}
    <form class="form-horizontal" action='{% url "auth:login" %}' method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <button type="submit">Enter</button><br>
    </form>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
    <form class="form-horizontal" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="authorization">
    </form>
{% endblock %}

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}

    {% block css %}
    {% endblock %}
</head>
<body>
{% include 'mainapp/includes/inc_menu.html' %}
<!-- test -->

{% block content %}
{% endblock %}

{% block js %}
{% endblock %}
</body>
</html>

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}

{% block title %}
    <title>Contacts</title>
{% endblock %}

{% block content %}
    <h1>Contacts!</h1>
{% endblock %}

mainapp/templates/mainapp/includes/inc_menu.html
<ul class="menu">
        <div class="menu-item">
            <a href="{% url 'main' %}"
               class="{% if request.resolver_match.url_name == 'main' %}
                        active
                      {% endif %}">
                Главная
            </a>
        </div>
        <div class="menu-item">
            <a href="{% url 'products:index' %}"
               class="{% if request.resolver_match.namespace == 'products' %}
                        active
                      {% endif %}">
                Продукты
            </a>
        </div>
        <div class="menu-item">
            <a href="{% url 'contacts' %}"
               class="{% if request.resolver_match.url_name == 'contacts' %}
                        active
                      {% endif %}">
                Контакты
            </a>
        </div>
</ul>

mainapp/templates/mainapp/main.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title%}
    <title>Main_page</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
<!--                                                     => static/css/styles.css when "load static"-->
{% endblock %}

{% block content %}
    <h1 class="test">Main Page!</h1>
    {% if request.user.is_authenticated %}
        <h2>Hello, {{ request.user.username|title }}</h2>
    {% else %}
        <h2>Hello!</h2>
    {% endif %}
    <ul>
    {%  for item in array %}
        <li>element {{ item }}</li>
    {% endfor %}
    </ul>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}

{% block title %}
    <title>Products</title>
{% endblock %}

{% block content %}
    <h1>Products all</h1>
    <ul>
        {%  for x in products %}
            <li>{{ x.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}